### ISSUE TITLE
crash if object is removed in design mode

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ObjectExplorer#2]
## ℹ Computer information

- VFP version: VFP 9 SP2 / VFPA
- ObjectExplorer version: n/a

## 📝 Provide detailed reproduction steps (if any)

1. Running ObjectExplorer while designing a class (FORM ends up the same, I think),
1. Closing the class shown in the ObjectExplorer
2. Select a different node in ObjectExplorer TreeView

### ✔️ Expected result

Message that class is missing or closing the ObjectExplorer

### ❌ Actual result

Errormessage

----
## Possible solution

This is in `treecontainer.GetBrowseCursorName`    
old   
```
Do Case
		* current node has own data session and cAlias
	Case Pemstatus(m.loCurrentObject, 'DataSessionID', 5)
		If Pemstatus(m.loCurrentObject, 'cAlias', 5)
```
new   
```
Do Case
        * object not found or released
    CASE ISNULL(m.loCurrentObject)
		* current node has own data session and cAlias
	Case Pemstatus(m.loCurrentObject, 'DataSessionID', 5)
		If Pemstatus(m.loCurrentObject, 'cAlias', 5)
```

**Comment by DougHennig** [comment]
Fixed in the latest release
