### ISSUE TITLE
Problem closing an object while ObjectExplorer is active

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ObjectExplorer#3]
## ℹ Computer information

- VFP version: VFP 9 SP2 / VFPA
- ObjectExplorer version: n/a

## 📝 Provide detailed reproduction steps (if any)

1. Running ObjectExplorer to an object instantiated (this shoud be no difference to a FORM, because a FORM is a special object)
1. Closing the Object

### ✔️ Expected result

Object closes, optimal with closing related ObjectExplorer instance.

### ❌ Actual result

Object does not close, because of unexpected reference in ObjectExplorer. Object possibly left in undefined state.

----
## Possible solution

An idea would be to EVENTBIND to QUERYUNLOAD and the similar events. Since one can run  ObjectExplorer to nonvisible objects one must check to not only work for objects based on FORM baseclass.

**Comment by DougHennig** [comment]
Fixed in the latest release. I just bound to QueryUnload for now.
