### ISSUE TITLE
Problem with THOR update

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ObjectExplorer#4]
## ℹ Computer information

- VFP version: VFP9 SP2 / VFPA
- ObjectExplorer version: 3.2.1

## 📝 Provide detailed reproduction steps (if any)

1. install via Thor
2. run scx in Thors folder

### ✔️ Expected result

Form should appear

### ❌ Actual result

Error message. The **VCX** is not existing in the folder, just the _vc2_ and the _vct_.

**Comment by DougHennig** [comment]
They are in the downloaded zip file, but for some reason they're failing to unzip. I've run into this before with another VFPX project (don't remember which one). I'm not sure what to do about it.

**Comment by lscheffler** [comment]
I have no idea about the Thor-internal process. The zip is the one in the repo to this project? At least 7zip unzips it manually. In the apps folder, there are only 5+1 files expanded
- explorer.sc2
- explorer.scx
- explorer.sct
- explorer.vc2
- explorer.vct   
and
- ObjectExplorerVersionFile.txt    

Checking the zip as a Hex dump, I see that those files are the first 5 in the zip file _explorer.vct_ is the next. This is true for  the order of files as well as for the catalogue.    
Try to
1. remove the *.??2, they have less value here
2. recreate the zip from scratch, possible manually and not with the scripting

**Comment by DougHennig** [comment]
I fixed the problem. VFPCompression.fll has a bug that prevents it from completely unzipping under some conditions (I reported this to Craig Boyd a couple of years ago but it hasn't been fixed as far as I know), so I updated Thor to use Shell.Application to do the unzipping instead.
