### ISSUE TITLE
Problem binding to non forms

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ObjectExplorer#5]
## ℹ Computer information

- VFP version: VFPA
- ObjectExplorer  version: 3.2.1

## 📝 Provide detailed reproduction steps (if any)

1. run Object Explorer against an non form bound object, for example empty bound to a variable

### ✔️ Expected result

Should be shown in ObjectExplorer

### ❌ Actual result

Error because `Queryunload` is missing

----
## Possible solution 
Replace like
```
		If PEMSTATUS(.oFirstObject, 'QueryUnload',5)
				bindevent(.oFirstObject, 'QueryUnload', This, 'OnObjectReleased')
		Endif

```
There is no good solution for other objects, as far as I see. Destroy is one of those events that will fire if there is code in it only, as far as I remember. And this will not help empty anyway. But I guess this risk must be taken. One might add a message if `Queryunload` is missing, but this is a nuisance.

**Comment by DougHennig** [comment]
Fixed in the latest release.
