### ISSUE TITLE
Problem hovering over CONTROL

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ObjectExplorer#6]
## ℹ Computer information

- VFP version: VFP9 SP2 / VFPA
- ObjectExplorer version: 3.2.2

## 📝 Provide detailed reproduction steps (if any)

1. Create a form with a object of _CONTROL _ baseclass
2. Run the form
3. hover over control
4. Start ObjectExplorer via hotkey

### ✔️ Expected result

- Object explorer shows to the possible depth
- Object explorer notify about problem to show controls _inner_ stuff

### ❌ Actual result

Error message because SYS(1270) tries to return the inside of the control, but this is hidden

## Possible solution

- Try catch the parameter - object 
- notify user
- Show form from THISFORM / or as close as possible to the control.

**Comment by DougHennig** [comment]
Fixed in the latest release
