### ISSUE TITLE
Problem with empty object

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ObjectExplorer#7]
## ℹ Computer information

- VFP version: VFP9 SP2 / VFPA
- ObjectExplorer version: 3.2.2

## 📝 Provide detailed reproduction steps (if any)

1. Create an empty object with some properties 
2. Start ObjectExplorer with empty object as parameter

### ✔️ Expected result

ObjectExplorer shows properties. 

### ❌ Actual result

Fail

**Comment by DougHennig** [comment]
Fixed in the latest release
