### ISSUE TITLE
Problem opening a form in object explorer....through Thor

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/ObjectExplorer#9]
## ℹ Computer information

- VFP version: 9 and Adv
- ObjectExplorer version: Current shipped with Thor

## 📝 Provide detailed reproduction steps (if any)

1. … Not sure if this is a Thor issue or an object explorer issue. Trying to open the object explorer on a current form
2. … Error during treecontainer init
3. … it is trying to access _Screen.oISXOptions.oKeyWordList but looking at the oISXOptions structure it should not have an o...jusr keywordlist which is an array. So either array is missing the o....or this init should exclude the o in the name.

### ✔️ Expected result

Expected to just have the object explorer to open.

### ❌ Actual result

Cannot get object explorer to open because of the error during the init method.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/34104227/169362687-ffb4a067-7885-48c5-b753-bc6962833168.png)

**Comment by DougHennig** [comment]
It works for me, so I'm not sure why you're getting the error. However, I added a TRY around that code so that should prevent the error for you.
